# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: iSponsorBlockTV add-on
version: "1.0.1"
slug: isponsorblocktv
description: SponsorBlock client for all YouTube TV clients.
url: "https://github.com/spy14/ha-addons/tree/main/isponsorblocktv"
arch:
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  apikey: null # get youtube apikey: https://developers.google.com/youtube/registering_an_application
  devices: []
  channel_whitelist: []
  skip_categories: []
  skip_count_tracking: false
  mute_ads: false
  skip_ads: true
schema:
  apikey: "str"
  devices:
    - name: "str?"
      screen_id: "str"
      offset: "int?"
  channel_whitelist:
    - id: "str"
    - name: "str"
  skip_categories:
    - match(^.*(sponsor|selfpromo|exclusive_access|interaction|poi_highlight|intro|outro|preview|filler|music_offtopic).*$)
  skip_count_tracking: "bool"
  mute_ads: "bool"
  skip_ads: "bool"
image: "ghcr.io/spy14/{arch}-addon-isponsorblocktv"
host_network: true
